version: "3"
services:
  pytest:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env-test
    environment:
      - PG_DATABASE_HOSTNAME=pytest-postgres
    command: "sh -c 'pytest -s -v --disable-warnings'"
    depends_on:
      - pytest-postgres

  pytest-postgres:
    image: postgres
    env_file:
      - .env-test
    environment:
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
      POSTGRES_USER: ${PG_DATABASE_USERNAME}
      POSTGRES_DB: ${PG_DATABASE_NAME}
    volumes:
      - pytest-postgres-db:/var/lib/postgresql/data
    ports:
      - "5441:5432"

volumes:
  pytest-postgres-db: