version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    environment:
      - PG_DATABASE_HOSTNAME=postgres
#    command:
#      - bash -c "alembic upgrade head"
#      - uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    command: "sh -c 'alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload'"
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
      POSTGRES_USER: ${PG_DATABASE_USERNAME}
      POSTGRES_DB: ${PG_DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5440:5432"

volumes:
  postgres-db: